# Generated by Django 2.2 on 2019-08-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_project_tech_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_template',
            field=models.URLField(blank=True, null=True),
        ),
    ]
