# Generated by Django 2.2 on 2019-08-09 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_project_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 7200)),
        ),
    ]
