# Generated by Django 2.2 on 2019-08-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='ide_stack',
            field=models.CharField(choices=[('node-js', 'NodeJS'), ('python', 'Python'), ('android', 'Android'), ('angular', 'Angular'), ('php', 'PHP')], default='node-js', max_length=140),
        ),
    ]
