# Generated by Django 2.2 on 2020-10-01 11:44

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('project_type', models.CharField(choices=[('website', 'Website'), ('android-App', 'Android App'), ('ios-App', 'Ios App'), ('sesktop-App', 'Desktop Application')], default='website', max_length=40)),
                ('team_size', models.CharField(choices=[('single_dev', 'Single Developer'), ('team', 'Multiple Developers')], default='single_dev', max_length=20)),
                ('budget', models.IntegerField(default=15)),
                ('timeline', models.DurationField(default=datetime.timedelta(seconds=7200))),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EscrowPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=15)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('paid_at', models.DateTimeField(auto_now=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
