# Generated by Django 2.2 on 2021-02-22 12:03

import datetime
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0019_auto_20200430_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(blank=True, max_length=300)),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=140), blank=True, null=True, size=3, unique=True)),
                ('channel_url', models.CharField(blank=True, editable=False, max_length=300, null=True)),
                ('messages', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('name', models.CharField(blank=True, max_length=140)),
                ('unread_counts', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('amount', models.IntegerField(default=15)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('escrow_disbursed', models.BooleanField(default=False)),
                ('stage', models.TextField(blank=True)),
                ('developer_note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('tools', models.TextField(blank=True, null=True)),
                ('project_type', models.CharField(choices=[('website', 'Website'), ('android-App', 'Android App'), ('ios-App', 'Ios App'), ('desktop-App', 'Desktop Application')], default='website', max_length=40)),
                ('team_size', models.CharField(choices=[('single_dev', 'Single Developer'), ('team', 'Multiple Developers')], default='single_dev', max_length=20)),
                ('budget', models.IntegerField(default=1000)),
                ('designbudget', models.IntegerField(default=0)),
                ('timeline', models.DurationField(default=datetime.timedelta(days=14))),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('stage', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('sign_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer', to='accounts.Profile')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='accounts.Profile')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='myteam', max_length=120)),
                ('members', models.TextField(blank=True)),
                ('pending', models.TextField(blank=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='remote_codeln.RemoteProject')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('todo', 'Todo'), ('inprogress', 'In Progress'), ('done', 'Done')], default='todo', max_length=40)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_codeln.ProjectFeature')),
            ],
        ),
        migrations.CreateModel(
            name='Signatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteDeveloper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_codeln.RemoteProject')),
            ],
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='remote_codeln.RemoteDeveloper'),
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_codeln.RemoteProject'),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='myteam', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('arbitration_required', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('tag', models.CharField(blank=True, max_length=120)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_codeln.ProjectFeature')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('files', models.TextField(blank=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='remote_codeln.RemoteProject')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_story', models.TextField(blank=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_codeln.ProjectFeature')),
            ],
        ),
        migrations.CreateModel(
            name='EscrowPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=15)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('paid_at', models.DateTimeField(auto_now=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='remote_codeln.RemoteProject')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_codeln.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField(blank=True, default=15, null=True)),
                ('timeline', models.DurationField(default=datetime.timedelta(days=14))),
                ('tools', models.TextField(blank=True, null=True)),
                ('shortlisted', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('proposal', models.TextField(blank=True)),
                ('withdraw', models.BooleanField(default=False)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='remote_codeln.RemoteProject')),
            ],
        ),
    ]
