# Generated by Django 2.2 on 2020-10-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0003_auto_20201015_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='tools',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remoteproject',
            name='tools',
            field=models.TextField(blank=True, null=True),
        ),
    ]
