# Generated by Django 2.2 on 2020-10-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0004_auto_20201015_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfeature',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
