# Generated by Django 2.2 on 2020-10-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0004_auto_20201015_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
