# Generated by Django 2.2 on 2020-10-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0005_issue_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
