# Generated by Django 2.2 on 2020-10-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0005_auto_20201022_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteproject',
            name='project_type',
            field=models.CharField(choices=[('website', 'Website'), ('android-App', 'Android App'), ('ios-App', 'Ios App'), ('desktop-App', 'Desktop Application')], default='website', max_length=40),
        ),
    ]
