# Generated by Django 2.2 on 2020-10-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0006_auto_20201023_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteproject',
            name='design_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='remoteproject',
            name='budget',
            field=models.IntegerField(default=1000),
        ),
    ]
