# Generated by Django 2.2 on 2020-11-20 12:20

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0006_auto_20201015_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(blank=True, max_length=300)),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=140), blank=True, null=True, size=3, unique=True)),
                ('channel_url', models.CharField(blank=True, editable=False, max_length=300, null=True)),
                ('messages', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('name', models.CharField(blank=True, max_length=140)),
                ('unread_counts', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='remoteproject',
            name='project_type',
            field=models.CharField(choices=[('website', 'Website'), ('android-App', 'Android App'), ('ios-App', 'Ios App'), ('Desktop-App', 'Desktop Application')], default='website', max_length=40),
        ),
    ]
