# Generated by Django 2.2 on 2020-10-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0007_auto_20201023_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remoteproject',
            old_name='design_budget',
            new_name='designbudget',
        ),
    ]
