# Generated by Django 2.2 on 2020-10-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0008_auto_20201023_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteproject',
            name='stage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
