# Generated by Django 2.2 on 2020-10-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0009_remoteproject_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='proposal',
            field=models.TextField(blank=True),
        ),
    ]
