# Generated by Django 2.2 on 2020-10-27 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0010_bid_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
