# Generated by Django 2.2 on 2020-10-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0012_bid_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfeature',
            name='stage',
            field=models.TextField(blank=True),
        ),
    ]
