# Generated by Django 2.2 on 2020-10-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0015_auto_20201029_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tag',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
