# Generated by Django 2.2 on 2020-10-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0017_remoteproject_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfeature',
            name='developer_note',
            field=models.TextField(blank=True),
        ),
    ]
