# Generated by Django 2.2 on 2020-11-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0018_projectfeature_developer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteproject',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
