# Generated by Django 2.2 on 2020-11-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0021_team_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='myteam', max_length=120),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(default='myteam', max_length=120),
        ),
    ]
