# Generated by Django 2.2 on 2020-11-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0022_auto_20201106_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pending',
            field=models.TextField(blank=True),
        ),
    ]
