# Generated by Django 2.2 on 2020-11-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0024_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteproject',
            name='client_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remoteproject',
            name='developer_sign',
            field=models.BooleanField(default=False),
        ),
    ]
