# Generated by Django 2.2 on 2020-11-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_codeln', '0027_auto_20201112_1046'),
        ('remote_codeln', '0007_auto_20201120_1220'),
    ]

    operations = [
    ]
