# Generated by Django 2.2 on 2020-01-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_enterpriseproject_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriseproject',
            name='slug',
        ),
    ]
