# Generated by Django 2.2 on 2020-01-22 12:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_enterpriseproject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisedeveloper',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprisedeveloper',
            name='project_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enterprisedeveloper',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprisedeveloperreport',
            name='report_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enterpriseproject',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, null=True),
        ),
        migrations.CreateModel(
            name='WebHookSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('webhook_event', models.CharField(blank=True, choices=[('on_test_complete', 'Test Complete'), ('on_report_ready', 'Report Ready')], default='test_complete', max_length=140, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Enterprise')),
            ],
        ),
    ]
