# Generated by Django 2.2 on 2020-02-10 15:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200122_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisedeveloperreport',
            name='competency',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisedeveloperreport',
            name='grading',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisedeveloperreport',
            name='requirements',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
