# Generated by Django 2.2 on 2020-04-27 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_idetemporaluser_email'),
        ('api', '0006_enterprisedeveloperreport_code_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisedeveloper',
            name='temp_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.IdeTemporalUser'),
        ),
    ]
