# Generated by Django 2.2 on 2020-04-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_enterprisedeveloper_temp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisedeveloper',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, null=True, unique=False),
        ),
    ]
