# Generated by Django 2.2 on 2020-03-22 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0043_auto_20200221_1128'),
        ('accounts', '0012_auto_20200117_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('satisfied', models.BooleanField(default=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Job')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('codeln_survey', 'CODELN SURVEY'), ('dev_survey', 'DEV SURVEY'), ('job_survey', 'JOB SURVEY')], default='codeln_survey', max_length=140)),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('feedback_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.RecruiterFeedback')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='feedback.SurveyQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=50, verbose_name='Choice')),
                ('position', models.IntegerField(verbose_name='position')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='feedback.SurveyQuestion')),
            ],
            options={
                'ordering': ('position',),
                'unique_together': {('question', 'choice'), ('question', 'position')},
            },
        ),
    ]
