# Generated by Django 2.2 on 2020-03-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterfeedback',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
