# Generated by Django 2.2 on 2020-03-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20200326_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterfeedback',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, null=True),
        ),
    ]
