# Generated by Django 2.2 on 2020-03-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20200326_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterfeedback',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, null=True, unique=True),
        ),
    ]
