# Generated by Django 2.2 on 2019-08-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_auto_20190802_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='devrequest',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
