# Generated by Django 2.2 on 2019-08-20 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_auto_20190819_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devrequest',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devaccount', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='devrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devs', to='accounts.Profile'),
        ),
    ]
