# Generated by Django 2.2 on 2019-08-20 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_auto_20190820_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobrecruiter', to='accounts.Profile'),
        ),
    ]
