# Generated by Django 2.2 on 2019-08-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_auto_20190820_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='devrequest',
            name='projectstarttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='projectstarttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
