# Generated by Django 2.2 on 2019-08-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0030_auto_20190822_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='devrequest',
            name='offerletter',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='devrequest',
            name='offerstatus',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='offerletter',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='offerstatus',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
