# Generated by Django 2.2 on 2019-08-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0031_auto_20190826_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='devrequest',
            name='demolink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='demolink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
