# Generated by Django 2.2 on 2019-10-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0032_auto_20190828_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='carted',
            field=models.BooleanField(default=False),
        ),
    ]
