# Generated by Django 2.2 on 2019-10-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0033_jobapplication_carted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='type',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
