# Generated by Django 2.2 on 2019-10-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0034_jobapplication_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='type',
            field=models.CharField(default='applied', max_length=500, null=True),
        ),
    ]
