# Generated by Django 2.2 on 2020-01-07 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0036_job_city'),
    ]

    operations = [


    ]
