# Generated by Django 2.2 on 2020-01-07 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0037_auto_20200107_1231'),
    ]

    operations = [


    ]
