# Generated by Django 2.2 on 2020-01-07 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0038_auto_20200107_1233'),
    ]

    operations = [

    ]
