# Generated by Django 2.2 on 2020-01-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0039_auto_20200107_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tag',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
