# Generated by Django 2.2 on 2020-01-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0040_job_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
