# Generated by Django 2.2 on 2020-01-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0041_auto_20200107_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='devrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
