# Generated by Django 2.2 on 2020-02-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0042_auto_20200115_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='framework',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='testendtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='teststarttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
