# Generated by Django 2.2 on 2020-04-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0044_auto_20200416_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='rejectioncomment',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='rejectionreason',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
