# Generated by Django 2.2 on 2020-06-12 10:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0045_auto_20200421_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_base', models.URLField(blank=True, null=True)),
                ('requirements', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('competency', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('grading', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('skill', models.CharField(blank=True, max_length=100, null=True)),
                ('report_ready', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='devrequest',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.DeveloperReport'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.DeveloperReport'),
        ),
    ]
