# Generated by Django 2.2 on 2020-06-12 11:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0046_auto_20200612_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerreport',
            name='code_base',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='developerreport',
            name='competency',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='developerreport',
            name='grading',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='developerreport',
            name='requirements',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
