# Generated by Django 2.2 on 2020-06-12 11:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0047_auto_20200612_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerreport',
            name='code_base',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developerreport',
            name='competency',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developerreport',
            name='requirements',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
