# Generated by Django 2.2 on 2020-06-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0049_auto_20200617_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='commission',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='years_experience',
            field=models.CharField(choices=[('0-1', '0-1'), ('1-2', '1-2'), ('2-4', '2-4'), ('4-above', '4-above')], default='2-4', max_length=30),
        ),
    ]
