# Generated by Django 2.2 on 2020-06-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0050_auto_20200619_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='years_experience',
            field=models.CharField(choices=[('0-3', '0-3'), ('3-5', '3-5'), ('5-above', '5-above')], default='3-5', max_length=30),
        ),
    ]
