# Generated by Django 2.2 on 2020-06-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0053_auto_20200622_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='terms',
            field=models.BooleanField(default=False),
        ),
    ]
