# Generated by Django 2.2 on 2020-06-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0054_job_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='years_experience',
            field=models.CharField(choices=[('0-1', '0-1'), ('1-3', '1-3'), ('3-above', '3-above')], default='1-3', max_length=30),
        ),
    ]
