# Generated by Django 2.2 on 2020-12-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0055_auto_20200623_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='remuneration',
            field=models.CharField(blank=True, help_text='in dollars ($)', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
