# Generated by Django 2.2.21 on 2021-06-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0059_job_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='repo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='framework',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='interviewstatus',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='offerletter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='offerstatus',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
