# Generated by Django 2.2 on 2019-09-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [

    ]
