# Generated by Django 2.2 on 2019-09-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student',
            field=models.BooleanField(default=False),
        ),
    ]
