# Generated by Django 2.2 on 2019-09-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_student'),
    ]

    operations = [

    ]
