# Generated by Django 2.2 on 2019-09-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_salary'),
    ]

    operations = [

    ]
