# Generated by Django 2.2 on 2019-09-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190927_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='availabilty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
