# Generated by Django 2.2 on 2020-01-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190927_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
    ]
