# Generated by Django 2.2 on 2020-01-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notifications',
            field=models.BooleanField(default=True),
        ),
    ]
