# Generated by Django 2.2 on 2020-03-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_referral_referralcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.UUIDField(default='', editable=False, null=True, unique=True),
        ),
    ]
