# Generated by Django 2.2 on 2020-03-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200327_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.SlugField(default='', editable=False, null=True, unique=True),
        ),
    ]
