# Generated by Django 2.2 on 2020-04-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200426_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='idetemporaluser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
