# Generated by Django 2.2 on 2020-04-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_idetemporaluser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='remote_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='remote_verified',
            field=models.BooleanField(default=False),
        ),
    ]
