# Generated by Django 2.2 on 2021-03-05 13:08

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200430_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
