# Generated by Django 2.2.20 on 2021-04-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_profile_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='design_portfolio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
