# Generated by Django 2.2.20 on 2021-05-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_profile_design_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github_repo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
