# Generated by Django 2.2.21 on 2021-06-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210526_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stage',
            field=models.CharField(choices=[('profile_type_selection', 'profile_type_selection'), ('recruiter_filling_details', 'recruiter_filling_details'), ('developer_filling_details', 'developer_filling_details'), ('complete', 'complete')], default='profile_type_selection', max_length=100),
        ),
    ]
