# Generated by Django 2.2 on 2019-08-09 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_framework_ide_stack'),
        ('frontend', '0020_auto_20190729_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('invite_accepted', 'Invite Accepted'), ('time_set', 'Time Set'), ('link_available', 'Link Available'), ('in_progress', 'In Progress'), ('project_completed', 'Project Completed'), ('analysis_started', 'Analysis Started'), ('transfer_complete', 'Transfer Complete'), ('analysis_complete', 'Analysis Complete')], default='invite_accepted', max_length=100)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Report')),
            ],
        ),
    ]
