# Generated by Django 2.2 on 2019-08-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_assessmentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentreport',
            name='github',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
