# Generated by Django 2.2 on 2019-08-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_auto_20190812_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentreport',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
