# Generated by Django 2.2 on 2019-08-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_auto_20190812_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentreport',
            name='github',
        ),
        migrations.RemoveField(
            model_name='assessmentreport',
            name='grading',
        ),
        migrations.RemoveField(
            model_name='assessmentreport',
            name='keycompitency',
        ),
        migrations.RemoveField(
            model_name='assessmentreport',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='assessmentreport',
            name='score',
        ),
    ]
