# Generated by Django 2.2 on 2019-08-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_assessmentreport_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentreport',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
