# Generated by Django 2.2 on 2019-08-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_auto_20190826_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='stage',
            field=models.CharField(default='invite_accepted', max_length=100),
        ),
    ]
