# Generated by Django 2.2 on 2019-08-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0030_auto_20190826_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='stage',
            field=models.CharField(choices=[('invite_accepted', 'Invite Accepted'), ('time_set', 'Time Set'), ('link_available', 'Link Available'), ('in_progress', 'In Progress'), ('project_completed', 'Project Completed'), ('analysis_started', 'Analysis Started'), ('transfer_complete', 'Transfer Complete'), ('analysis_complete', 'Analysis Complete')], default='invite_accepted', max_length=100),
        ),
    ]
