# Generated by Django 2.2 on 2019-08-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0032_assessment_projectstarttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='frameworktested',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
