# Generated by Django 2.2 on 2019-08-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0033_assessment_frameworktested'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='demolink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
