# Generated by Django 2.2 on 2019-08-28 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0034_assessment_demolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateexperience', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateportfolio', to='accounts.Profile'),
        ),
    ]
