# Generated by Django 2.2 on 2019-08-30 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0037_auto_20190830_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Report'),
        ),
    ]
