# Generated by Django 2.2 on 2019-09-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0039_auto_20190830_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='manualtest',
            field=models.BooleanField(default=False),
        ),
    ]
