# Generated by Django 2.2 on 2019-10-07 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0041_auto_20190901_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='test_mode',
        ),
        migrations.AddField(
            model_name='assessment',
            name='test_choice',
            field=models.CharField(choices=[('on_site_test', 'On Site Test'), ('automated_test', 'Automated Test')], default='automated_test', max_length=100),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='stage',
            field=models.CharField(blank=True, choices=[('invite_accepted', 'Invite Accepted'), ('time_set', 'Time Set'), ('link_available', 'Link Available'), ('in_progress', 'In Progress'), ('project_completed', 'Project Completed'), ('analysis_started', 'Analysis Started'), ('transfer_complete', 'Transfer Complete'), ('analysis_complete', 'Analysis Complete')], default='invite_accepted', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='test_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.TestCenter'),
        ),
    ]
