# Generated by Django 2.2 on 2019-10-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0047_auto_20191007_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcenter',
            name='end_time',
        ),
    ]
