# Generated by Django 2.2 on 2019-10-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0048_remove_testcenter_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcenter',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
