# Generated by Django 2.2 on 2019-10-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0049_testcenter_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcenter',
            name='start_time',
        ),
    ]
