# Generated by Django 2.2 on 2019-10-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0050_remove_testcenter_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcenter',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
