# Generated by Django 2.2 on 2020-03-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0051_testcenter_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('discord', models.CharField(max_length=300, null=True)),
                ('members', models.CharField(max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('link', models.CharField(max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(blank=True, max_length=300, null=True)),
                ('likes', models.CharField(blank=True, max_length=300, null=True)),
                ('tags', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
