# Generated by Django 2.2 on 2020-03-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0021_auto_20190915_2012'),
        ('frontend', '0052_cohort_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.Subject'),
        ),
    ]
