# Generated by Django 2.2 on 2020-03-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0053_resources_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
