# Generated by Django 2.2 on 2020-03-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0055_auto_20200304_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='csa',
            field=models.BooleanField(default=False),
        ),
    ]
