# Generated by Django 2.2 on 2020-03-11 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0062_auto_20200310_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Portfolio'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='members',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
