# Generated by Django 2.2 on 2020-04-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0083_auto_20200421_1219'),
        ('frontend', '0085_auto_20200427_1631'),
    ]

    operations = [
    ]
