# Generated by Django 2.2 on 2021-03-05 13:08

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0110_auto_20210226_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Portfolio'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='frontend_po_search__549366_gin'),
        ),
    ]
