# Generated by Django 2.2.21 on 2021-06-28 10:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0115_auto_20210626_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='company_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='images',
            field=separatedvaluesfield.models.SeparatedValuesField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='personal_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_end_month',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_role',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_start_month',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Portfolio'),
        ),
    ]
