# Generated by Django 2.2.21 on 2021-07-05 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0119_auto_20210630_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='demo_link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='repository_link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
