# Generated by Django 2.2.21 on 2021-07-06 08:19

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0121_auto_20210706_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='location',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
