# Generated by Django 2.2 on 2019-08-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='data',
        ),
        migrations.AddField(
            model_name='job',
            name='setup_code',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
