# Generated by Django 2.2 on 2021-02-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0019_auto_20200430_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('category', models.CharField(blank=True, choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('mobile', 'Mobile'), ('java', 'Java'), ('python', 'Python')], default='frontend', max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('developers', models.ManyToManyField(blank=True, related_name='dev_list', to='accounts.Profile')),
            ],
        ),
    ]
