# Generated by Django 2.2 on 2019-08-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_auto_20190820_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='quizzes',
        ),
    ]
