# Generated by Django 2.2 on 2019-08-20 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_remove_student_quizzes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomquiz',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempanswers', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='takenquiz',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='accounts.Profile'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
