# Generated by Django 2.2 on 2019-08-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_auto_20190820_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=250),
        ),
    ]
