# Generated by Django 2.2 on 2019-08-21 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_auto_20190820_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='randomquiz',
            name='questions',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
