# Generated by Django 2.2 on 2019-08-21 01:38

from django.db import migrations
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0017_auto_20190821_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomquiz',
            name='questions',
            field=separatedvaluesfield.models.SeparatedValuesField(max_length=150, null=True),
        ),
    ]
