# Generated by Django 2.2 on 2019-08-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_auto_20190821_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomquiz',
            name='questions',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
