# Generated by Django 2.2 on 2019-09-15 20:11

from django.db import migrations, models
import django.db.models.deletion
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_auto_20190821_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomquiz',
            name='questions',
            field=separatedvaluesfield.models.SeparatedValuesField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='randomquiz',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile2', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile1', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='takenquiz',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.Profile'),
        ),
    ]
