# Generated by Django 2.2 on 2020-03-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0021_auto_20190915_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='syllabus',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
