# Generated by Django 2.2 on 2020-03-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0022_subject_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='provider',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
