# Generated by Django 2.2 on 2019-09-15 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('checked_out', models.BooleanField(default=False)),
                ('devspending', models.CharField(blank=True, max_length=900, null=True)),
                ('devspaid', models.CharField(blank=True, max_length=900, null=True)),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('transaction_id', models.CharField(blank=True, max_length=900, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
