# Generated by Django 2.2 on 2019-09-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='developerorder',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
