# Generated by Django 2.2 on 2019-09-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20190904_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerorder',
            name='price',
        ),
    ]
