# Generated by Django 2.2 on 2019-09-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_developerorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='devs',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.DeleteModel(
            name='DeveloperOrder',
        ),
    ]
