# Generated by Django 2.2 on 2019-09-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20190911_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='devs',
            new_name='devspaid',
        ),
        migrations.AddField(
            model_name='cart',
            name='devspending',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
