# Generated by Django 2.2 on 2019-09-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20190913_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
